language: bash

env:
  global:
    - TERRAFORM_VERSION=0.11.11

sudo: required

services:
  - docker

before_install:
  - docker pull hashicorp/terraform:$TERRAFORM_VERSION

script:
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:$TERRAFORM_VERSION validate -check-variables=false
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:$TERRAFORM_VERSION fmt -write=false -diff=true -check=true
