---

###
### Travis settings
###
sudo: required
services:
  - docker


###
### Installation
###
before_install: true
install: true

###
### Linting
###
before_script:
  - make lint


###
### Testing
###
script:
  - make test
