name: Flaconi Github Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: code-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Checkout private actions repo
        uses: actions/checkout@v7
        with:
          repository: Flaconi/github-actions
          ref: v1
          token: ${{ secrets.REPO_READ_TOKEN }}
          path: .github/_flaconi/github-actions

      - name: Run Flaconi Github Code Review
        uses: ./.github/_flaconi/github-actions/.github/workflows/github-code-review.yml
        with:
          gh_token: ${{ secrets.REPO_READ_TOKEN }}
          gh_copilot_token: ${{ secrets.COPILOT_GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
